# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/gabriel/PG/FiltroPB/FiltroPB.cache/wt [current_project]
set_property parent.project_path /home/gabriel/PG/FiltroPB/FiltroPB.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/gabriel/PG/Verilog/Deco_Sum.v
  /home/gabriel/PG/Verilog/DecosSuma.v
}
synth_design -top DecosSuma -part xc7a100tcsg324-1 -flatten_hierarchy none
write_checkpoint -noxdef DecosSuma.dcp
catch { report_utilization -file DecosSuma_utilization_synth.rpt -pb DecosSuma_utilization_synth.pb }
