# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {3}  -id {VRFC 10-278}  -string {{WARNING: [VRFC 10-278] actual bit length 32 differs from formal bit length 1 for port i0 [/home/gabriel/PG/Verilog/Sort.v:45]}}  -suppress 
set_msg_config  -ruleid {4}  -id {VRFC 10-278}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/gabriel/PG/AlgoritmoCorrelacion/AlgoritmoCorrelacion.cache/wt [current_project]
set_property parent.project_path /home/gabriel/PG/AlgoritmoCorrelacion/AlgoritmoCorrelacion.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/gabriel/PG/Verilog/SR_latch_gate.v
  /home/gabriel/PG/MovingAverage/MovingAverage.srcs/sources_1/new/mux2_1.v
  /home/gabriel/PG/Verilog/delayed_and.v
  /home/gabriel/PG/Verilog/thermo2bin.v
  /home/gabriel/PG/Verilog/Sort.v
  /home/gabriel/PG/Verilog/Sumatoria.v
  /home/gabriel/PG/Verilog/shiftRegister.v
  /home/gabriel/PG/Verilog/Multiplicador.v
  /home/gabriel/PG/MovingAverage/MovingAverage.srcs/sources_1/new/movingAverage.v
  /home/gabriel/PG/Verilog/FiltroPB.v
  /home/gabriel/PG/Verilog/Comparador.v
  /home/gabriel/PG/Verilog/AlgoritmoCorrelacion.v
}
synth_design -top AlgoritmoCorrelacion -part xc7a100tcsg324-1 -flatten_hierarchy full
write_checkpoint -noxdef AlgoritmoCorrelacion.dcp
catch { report_utilization -file AlgoritmoCorrelacion_utilization_synth.rpt -pb AlgoritmoCorrelacion_utilization_synth.pb }
