# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/gabriel/PG/AlgoritmoCorrelacion/AlgoritmoCorrelacion.cache/wt [current_project]
set_property parent.project_path /home/gabriel/PG/AlgoritmoCorrelacion/AlgoritmoCorrelacion.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib /home/gabriel/PG/MovingAverage/MovingAverage.srcs/sources_1/new/movingAverage.v
synth_design -top movingAverage -part xc7a100tcsg324-1 -flatten_hierarchy full
write_checkpoint -noxdef movingAverage.dcp
catch { report_utilization -file movingAverage_utilization_synth.rpt -pb movingAverage_utilization_synth.pb }
