# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/gabriel/PG/FPU_PRUEBAS/FPU_PRUEBAS.cache/wt [current_project]
set_property parent.project_path /home/gabriel/PG/FPU_PRUEBAS/FPU_PRUEBAS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/gabriel/PG/fpuuart/Add-Subt/Multiplexer_AC.v
  /home/gabriel/PG/fpuuart/Add-Subt/Rotate_Mux_Array.v
  /home/gabriel/PG/fpuuart/Add-Subt/RegisterAdd.v
  /home/gabriel/PG/fpuuart/Add-Subt/Comparator_Less.v
  /home/gabriel/PG/fpuuart/Add-Subt/shift_mux.v
  /home/gabriel/PG/fpuuart/Add-Subt/Greater_Comparator.v
  /home/gabriel/PG/fpuuart/Receptor.v
  /home/gabriel/PG/fpuuart/Transmisor.v
  /home/gabriel/PG/fpuuart/UBuffer.v
  /home/gabriel/PG/fpuuart/Add-Subt/Comparators.v
  /home/gabriel/PG/fpuuart/Add-Subt/Mux_Array.v
  /home/gabriel/PG/fpuuart/Add-Subt/sgn_result.v
  /home/gabriel/PG/fpuuart/Add-Subt/add_sub_carry_out.v
  /home/gabriel/PG/fpuuart/Add-Subt/Comparator.v
  /home/gabriel/PG/fpuuart/Add-Subt/MultiplexTxT.v
  /home/gabriel/PG/fpuuart/Add-Subt/Priority_Codec_32.v
  /home/gabriel/PG/fpuuart/Add-Subt/xor_tri.v
  /home/gabriel/PG/fpuuart/Add-Subt/Mux_3x1.v
  /home/gabriel/PG/fpuuart/Add-Subt/Priority_Codec_64.v
  /home/gabriel/PG/fpuuart/Coun_Baud.v
  /home/gabriel/PG/fpuuart/ReceptorRX.v
  /home/gabriel/PG/fpuuart/Transmisor_TX.v
  /home/gabriel/PG/fpuuart/Add-Subt/exp_operation.v
  /home/gabriel/PG/fpuuart/Add-Subt/Round_Sgf_Dec.v
  /home/gabriel/PG/fpuuart/Add-Subt/FSM_Add_Subtract.v
  /home/gabriel/PG/fpuuart/Add-Subt/Add_Subt.v
  /home/gabriel/PG/fpuuart/Add-Subt/Tenth_Phase.v
  /home/gabriel/PG/fpuuart/Add-Subt/Oper_Start_In.v
  /home/gabriel/PG/fpuuart/Add-Subt/Barrel_shifter.v
  /home/gabriel/PG/fpuuart/Add-Subt/LZD.v
  /home/gabriel/PG/fpuuart/Mux_4x1.v
  /home/gabriel/PG/fpuuart/ROM_test.v
  /home/gabriel/PG/fpuuart/cont_test.v
  /home/gabriel/PG/fpuuart/Mux_8x1.v
  /home/gabriel/PG/fpuuart/Uart.v
  /home/gabriel/PG/fpuuart/FSM_test.v
  /home/gabriel/PG/fpuuart/Add-Subt/FPU_Add_Subtract_Function.v
  /home/gabriel/PG/fpuuart/FPU_UART.v
}
read_xdc /home/gabriel/PG/fpuuart/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /home/gabriel/PG/fpuuart/Nexys4_Master.xdc]

synth_design -top FPU_UART -part xc7a100tcsg324-1
write_checkpoint -noxdef FPU_UART.dcp
catch { report_utilization -file FPU_UART_utilization_synth.rpt -pb FPU_UART_utilization_synth.pb }
