# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/gmarin/Documents/PG/Detector/Detector.cache/wt [current_project]
set_property parent.project_path C:/Users/gmarin/Documents/PG/Detector/Detector.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/gmarin/Documents/PG/Verilog/Multiplicador.v
  C:/Users/gmarin/Documents/PG/Verilog/FlagCounter.v
  C:/Users/gmarin/Documents/PG/Verilog/DecosSuma.v
  C:/Users/gmarin/Documents/PG/Verilog/BitsCounter.v
  C:/Users/gmarin/Documents/PG/Verilog/Pattern_Counter.v
  C:/Users/gmarin/Documents/PG/Verilog/FF_JK.v
  C:/Users/gmarin/Documents/PG/Verilog/Maquina_Estados.v
  C:/Users/gmarin/Documents/PG/Verilog/RegistroCorrelacion.v
  C:/Users/gmarin/Documents/PG/Verilog/Signal_Register.v
  C:/Users/gmarin/Documents/PG/Verilog/Correlacion.v
  C:/Users/gmarin/Documents/PG/Verilog/SimCorrelacion.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top SimCorrelacion -part xc7a100tcsg324-1


write_checkpoint -force -noxdef SimCorrelacion.dcp

catch { report_utilization -file SimCorrelacion_utilization_synth.rpt -pb SimCorrelacion_utilization_synth.pb }
