# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/gabriel/PG/BubbleSorting/BubbleSorting.cache/wt [current_project]
set_property parent.project_path /home/gabriel/PG/BubbleSorting/BubbleSorting.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/gabriel/PG/Verilog/SR_latch_dataflow.v
  /home/gabriel/PG/Verilog/SR_latch_gate.v
  /home/gabriel/PG/Verilog/delayed_and.v
  /home/gabriel/PG/MovingAverage/MovingAverage.srcs/sources_1/new/mux2_1.v
  /home/gabriel/PG/Verilog/Sort.v
  /home/gabriel/PG/Verilog/Sumatoria.v
  /home/gabriel/PG/Verilog/thermo2bin.v
}
synth_design -top Sumatoria -part xc7a100tcsg324-1
write_checkpoint -noxdef Sumatoria.dcp
catch { report_utilization -file Sumatoria_utilization_synth.rpt -pb Sumatoria_utilization_synth.pb }
