# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/gabriel/project_2/project_2.cache/wt [current_project]
set_property parent.project_path /home/gabriel/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/gabriel/project_2/project_2.srcs/sources_1/new/Deco_Sum.v
  /home/gabriel/project_2/project_2.srcs/sources_1/new/Signal_Register.v
  /home/gabriel/project_2/project_2.srcs/sources_1/new/Sumatoria.v
  /home/gabriel/project_2/project_2.srcs/sources_1/new/RegistroCorrelacion.v
  /home/gabriel/project_2/project_2.srcs/sources_1/new/Pattern_Counter.v
  /home/gabriel/project_2/project_2.srcs/sources_1/new/Multiplicador.v
  /home/gabriel/project_2/project_2.srcs/sources_1/new/Maquina_Estados.v
  /home/gabriel/project_2/project_2.srcs/sources_1/new/FlagCounter.v
  /home/gabriel/project_2/project_2.srcs/sources_1/new/FF_JK.v
  /home/gabriel/project_2/project_2.srcs/sources_1/imports/new/DecosSuma.v
  /home/gabriel/project_2/project_2.srcs/sources_1/new/BitsCounter.v
  /home/gabriel/project_2/project_2.srcs/sources_1/new/Correlacion.v
}
synth_design -top Correlacion -part xc7a100tcsg324-1
write_checkpoint -noxdef Correlacion.dcp
catch { report_utilization -file Correlacion_utilization_synth.rpt -pb Correlacion_utilization_synth.pb }
